#!/usr/bin/env node
/**
 * A machine-readable summary of the documentation.
 *
 * **Offered, not asserted as a standard.** The convention this follows exists as
 * a proposal with a small number of adopters. Serving one costs nothing and is
 * harmless; presenting it as an industry standard would be a claim we cannot
 * source, so the header says `llms.txt` and nothing more about its standing.
 *
 * Written at build time rather than served by a route, because the site's output
 * is static and a route that computed this on demand would need a server. That
 * means it cannot describe a page the build did not produce, which is the
 * property worth having: a summary listing a page that 404s is worse than no
 * summary.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const SITE = fileURLToPath(new URL("..", import.meta.url));
const CONTENT = join(SITE, "src/content/docs");
const OUT = join(SITE, "public/llms.json");

/**
 * The frontmatter of one page.
 *
 * A five-line reader rather than a YAML dependency: the frontmatter this site
 * uses is a flat list of `key: value` and a title that may be quoted. Anything
 * richer is a signal to add a real parser rather than to grow a regex.
 */
function frontmatter(source) {
	if (!source.startsWith("---")) {
		return {};
	}
	const end = source.indexOf("\n---", 3);
	if (end === -1) {
		return {};
	}
	const data = {};
	for (const line of source.slice(3, end).split(/\r?\n/)) {
		const match = /^([A-Za-z][A-Za-z0-9_]*):\s*(.*)$/.exec(line);
		if (match === null) {
			continue;
		}
		data[match[1]] = match[2].trim().replace(/^["']|["']$/g, "");
	}
	return data;
}

function walk(dir) {
	const found = [];
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const path = join(dir, entry.name);
		if (entry.isDirectory()) {
			found.push(...walk(path));
			continue;
		}
		if (/\.mdx?$/.test(entry.name)) {
			found.push(path);
		}
	}
	return found;
}

const pages = walk(CONTENT)
	.map((path) => ({
		path,
		// The URL the page is served at, not a path. `index` at the root becomes
		// "/" and every other page keeps its directory form, because the build emits
		// directory-style URLs — a summary listing `//quickstart` would be a summary
		// nobody could fetch.
		slug: `/${path
			// Separators normalised *before* the content directory is stripped, and
			// the leading separator the strip leaves is removed. Skipping either
			// step yields `//page` — a valid-looking string that fetches nothing,
			// and the kind of thing a generator produces silently.
			.replace(/\\/g, "/")
			.replace(CONTENT.replace(/\\/g, "/"), "")
			.replace(/^\/index\.mdx?$/, "")
			.replace(/\/index\.mdx?$/, "/")
			.replace(/\.mdx?$/, "")
			.replace(/^\//, "")}`,
		...frontmatter(readFileSync(path, "utf8")),
	}))
	// Drafts are in the source tree and not in the built site, so listing one here
	// would be listing a URL that 404s. Filtered rather than trusted, because a
	// page that is drafted and linked before it ships is an ordinary thing to have.
	.filter((page) => page.draft === "false")
	.sort((a, b) => a.slug.localeCompare(b.slug))
	.map((page) => ({
		title: page.title ?? page.slug,
		...(page.description === undefined
			? {}
			: { description: page.description }),
		url: page.slug,
	}));

const constants = readFileSync(
	join(SITE, "../../packages/core/src/constants.ts"),
	"utf8",
);
const draft = /draft:\s*"([^"]+)"/.exec(constants)?.[1] ?? "unknown";
const commit = /commit:\s*"([^"]+)"/.exec(constants)?.[1] ?? "unknown";

writeFileSync(
	OUT,
	`${JSON.stringify(
		{
			// Named per the convention's own filename rather than a format this
			// project defines, so a consumer can tell what it is looking at.
			name: "ax-kit documentation",
			url: "https://ax-kit.dev",
			specification: {
				name: "WebMCP",
				draft,
				commit,
				url: "https://webmachinelearning.github.io/webmcp/",
			},
			note: "This file is generated by the documentation build. It lists only pages the build produced; a drafted page does not appear.",
			pages,
		},
		null,
		"\t",
	)}\n`,
	"utf8",
);

process.stdout.write(`[llms.json] indexed ${pages.length} pages\n`);
